version: "3.8"

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:5173
    env_file:
      - ./client/.env
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.Server
    ports:
      - 5000:5000
    env_file:
      - ./server/.env
    depends_on:
      - "db"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "'db.stats().ok'"]
      interval: 10s
      timeout: 5s
      retries: 3
  socket:
    build:
      context: ./server
      dockerfile: Dockerfile.Socket
    ports:
      - 3001:3001
    env_file:
      - ./server/.env
    depends_on:
      - "db"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "'db.stats().ok'"]
      interval: 10s
      timeout: 5s
      retries: 3
  db:
    image: mongo
    ports:
      - 27017:27017
